# Load D4M Module
include("loadD4M.jl")

# Run Assoc Intro Example
println("Running AI1_SetupTEST")
include("1Intro/1AssocIntro/AI1_SetupTEST.jl")
println("Running AI2_SubsrefTEST")
include("1Intro/1AssocIntro/AI2_SubsrefTEST.jl")
println("Running AI3_MathTEST")
include("1Intro/1AssocIntro/AI3_MathTEST.jl")
println("Running AI4_AdvConstructTEST")
include("1Intro/1AssocIntro/AI4_AdvConstructTEST.jl")

# Run Edge Art Example
println("Running EA1_GraphTEST")
include("1Intro/2EdgeArt/EA1_GraphTEST.jl")
println("Running EA2_SubsrefTEST")
include("1Intro/2EdgeArt/EA2_SubsrefTEST.jl")
println("Running EA3_SubGraphTEST")
include("1Intro/2EdgeArt/EA3_SubGraphTEST.jl")

# Run Entity Analysis Example
println("Running EA1_ReadTEST")
include("2Apps/1EntityAnalysis/EA1_ReadTEST.jl")
println("Running EA2_StatTEST")
include("2Apps/1EntityAnalysis/EA2_StatTEST.jl")
println("Running EA3_FacetTEST")
include("2Apps/1EntityAnalysis/EA3_FacetTEST.jl")
println("Running EA4_GraphTEST")
include("2Apps/1EntityAnalysis/EA4_GraphTEST.jl")
println("Running EA5_GraphQueryTEST")
include("2Apps/1EntityAnalysis/EA5_GraphQueryTEST.jl")
include("2Apps/2TrackAnalysis/findtrackgraph.jl")
include("2Apps/2TrackAnalysis/findtracks.jl")
println("Running TA1_BuildTEST")
include("2Apps/2TrackAnalysis/TA1_BuildTEST.jl")
println("Running TA2_QueryTEST")
include("2Apps/2TrackAnalysis/TA2_QueryTEST.jl")
println("Running TA3_GraphTEST")
include("2Apps/2TrackAnalysis/TA3_GraphTEST.jl")

# Run Parallel Database Example
println("Running pDB01_DataTEST")
include("3Scaling/2ParallelDatabase/pDB01_DataTEST.jl")
println("Running pDB02_FileTEST")
include("3Scaling/2ParallelDatabase/pDB02_FileTEST.jl")
println("Running pDB03_AssocTEST")
include("3Scaling/2ParallelDatabase/pDB03_AssocTEST.jl")
println("Running pDB04_DegreeTEST")
include("3Scaling/2ParallelDatabase/pDB04_DegreeTEST.jl")

# Run Matrix Performance Example
println("Running MP1_DenseTEST")
include("3Scaling/3MatrixPerformance/MP1_DenseTEST.jl")
println("Running MP2_SparseTEST")
include("3Scaling/3MatrixPerformance/MP2_SparseTEST.jl")
println("Running MP3_AssocTEST")
include("3Scaling/3MatrixPerformance/MP3_AssocTEST.jl")
println("Running MP4_AssocCatKeyTEST")
include("3Scaling/3MatrixPerformance/MP4_AssocCatKeyTEST.jl")
println("Running MP5_AssocCatValKeyTEST")
include("3Scaling/3MatrixPerformance/MP5_AssocCatValKeyTEST.jl")
println("Running MP6_AssocPlus")
include("3Scaling/3MatrixPerformance/MP6_AssocPlus.jl")
